config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  root "home#index"

  resources :analyze, only: %i[index create update destroy]

  get "/results/:id", to: "analyze#show", as: :results
  get "/progress/:id", to: "analyze#progress", as: :progress
  get "/results_groups", to: "keywords#show", as: :results_groups

  resources :keywords, only: %i[index create update destroy]
  resources :users

  namespace :api do
    resources :users, only: %i[create]
    resources :keywords, only: %i[index create update destroy]
  end
end

app/controllers/analyze_controller.rb
class AnalyzeController < ApplicationController
  before_action :set_keywords

  def index
    @analysis = Analysis.all.order(created_at: :desc)
  end

  def create
    username = params[:username]

    if username.blank?
      redirect_to root_path, alert: "Username obrigatório"
      return
    else
      begin
        ImportUserDataService.new(username).call
        user_id = User.find_by(username: username).id
        redirect_to progress_path(id: user_id), notice: "Análise iniciada para #{username}"
      rescue ImportUserDataService::UserNotFound
        redirect_to root_path, alert: "Usuário '#{username}' não encontrado na API"
      end
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    return render json: { error: "User not found" }, status: :not_found unless @user

    @analysis = @user.analysis
    return render json: { error: "Analysis not available yet" }, status: :processing unless @analysis

    group_stats = Analysis.all.map(&:stats)
    words = group_stats.map { |b| b&.values || 0 }.sum()

    render json: {
      user: @user.username,
      approved: @user.comments.approved.count,
      rejected: @user.comments.rejected.count,
      stats: @analysis.stats,
      group_stats: {
        users_analyzed: Analysis.count,
        mean: Analysis.mean(words),
        median: Analysis.median(words),
        std_dev: Analysis.std_dev(words)
      }
    }
  end

  def progress
    @user = User.find(params[:id])
    @total = @user.comments.count
    @processed = @user.comments.where.not(status: 'new').count
    @progress = (@processed.to_f / @total * 100).round(2)

    render json: {
      user: @user.username,
      total_comments: @total,
      processed_comments: @processed,
      progress: "#{(@processed.to_f / @total * 100).round(2)}%"
    }
  end

  private

  def set_keywords
    @keywords = Keyword.pluck(:id, :word)
  end
end

app/helpers/analyze_helper.rb
module AnalyzeHelper
end

app/views/analyze/index.html.erb
<div class="flex items-center m-5">
  <h1 class="text-2xl text-center text-primary mx-auto">
    Listagem de Analises
  </h1>
</div>

<div class="flex flex-col mt-10">
  <div class="overflow-x-auto">
    <table class="table-auto w-full text-sm font-semibold text-center">
      <thead class="text-base">
        <tr>
          <th>ID</th>
          <th>Usuário</th>
          <th>Quantidade Aprovados</th>
          <th>Quantidade Rejeitados</th>
          <th>Estatísticas</th>
        </tr>
      </thead>

      <tbody>
        <% @analysis.each_with_index do |analyze, index| %>
          <tr class="border-t border-black items-center <%= index % 2 == 0 ? "bg-gray-200" : "bg-gray-100" %>">
            <td><%= analyze.id %></td>
            <td><%= analyze.user.username %></td>
            <td><%= analyze.approved_count %></td>
            <td><%= analyze.rejected_count %></td>

            <td class="gap-5 h-20">
              <p><b class="text-primary">Média:</b> <%= analyze.stats["mean"] %></p>
              <p><b class="text-primary">Mediana:</b> <%= analyze.stats["median"] %></p>
              <p><b class="text-primary">Desvio Padrão:</b> <%= analyze.stats["std_dev"] %></p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/analyze/progress.html.erb
<h1>Progresso da análise para <%= @user.username %></h1>

<ul>
  <li>Total de comentários: <%= @total %></li>
  <li>Processados: <%= @processed %></li>
  <li>Progresso: <%= @progress %>%</li>
</ul>

<% if @processed < @total %>
  <p><strong>Atualize a página em alguns segundos...</strong></p>
<% else %>
  <%= link_to "Ver resultados", results_path(username: @user.username) %>
<% end %>

<%= link_to "Voltar", root_path %>

app/views/analyze/show.html.erb
<h1>Resultados para <%= @user.username %></h1>

<h2>Estatísticas Individuais</h2>
<ul>
  <li>Aprovados: <%= @approved %></li>
  <li>Rejeitados: <%= @rejected %></li>
  <li>Média de palavras: <%= @stats["mean"].round(2) %></li>
  <li>Mediana: <%= @stats["median"] %></li>
  <li>Desvio padrão: <%= @stats["std_dev"].round(2) %></li>
</ul>

<h2>Estatísticas do Grupo</h2>
<ul>
  <li>Usuários analisados: <%= @group_stats[:users_analyzed] %></li>
  <li>Média: <%= @group_stats[:mean].round(2) %></li>
  <li>Mediana: <%= @group_stats[:median] %></li>
  <li>Desvio padrão: <%= @group_stats[:std_dev].round(2) %></li>
</ul>

<%= link_to "Voltar", root_path %>