config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  root "home#index"

  resources :analyze, only: %i[index create update destroy]

  get "/results/:id", to: "analyze#show", as: :results
  get "/progress/:id", to: "analyze#progress", as: :progress
  get "/results_groups", to: "keywords#show", as: :results_groups

  resources :keywords, only: %i[index create update destroy]
  resources :users

  namespace :api do
    resources :users, only: %i[create]
    resources :keywords, only: %i[index create update destroy]
  end
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  validates :word, presence: true, uniqueness: true
end

app/controllers/api/keywords_controller.rb
module Api
  class KeywordsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
      keywords = Keyword.pluck(:word)

      render json: { keywords: keywords }, status: :ok
    end

    def create
      keyword = Keyword.new(keyword_params)
    
      if keyword.save
        ProcessKeywordJob.perform_later(keyword.id)

        sleep(2)
        group_stats = results_groups

        render json: { message: 'Palavra Chave criada com sucesso!', keyword: keyword, group_stats: group_stats }, status: :created
      else
        render json: { error: "Palavra chave já cadastrada." }, status: :unprocessable_entity
      end
    end

    def update
      keyword = Keyword.find(params[:id])
    
      if keyword.update(keyword_params)
        ProcessKeywordJob.perform_later(keyword.id)

        sleep(2)
        group_stats = results_groups

        render json: { message: 'Palavra Chave atualizada com sucesso!', keyword: keyword, group_stats: group_stats }, status: :created
      else
        render json: { error: "Palavra chave já cadastrada." }, status: :unprocessable_entity
      end
    end

    def destroy
      keyword = Keyword.find(params[:id])
      keyword.destroy

      ProcessKeywordJob.perform_later("")

      sleep(2)
      group_stats = results_groups

      render json: { message: 'Palavra Chave apagada com sucesso!', group_stats: group_stats }, status: :created
    end

    private

    def keyword_params
      params.require(:keyword).permit(:word)
    end

    def results_groups
      group_stats = Analysis.all.map(&:stats)
      words = group_stats.map { |b| b&.values || 0 }.sum()

      status = {
        users_analyzed: Analysis.count,
        mean: Analysis.mean(words),
        median: Analysis.median(words),
        std_dev: Analysis.std_dev(words)
      }

      sleep(2)
      status
    end
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def index
    @keywords = Keyword.all.order(created_at: :desc)
    @keyword = Keyword.new
  end

  def create
    @keyword = Keyword.new(keyword_params)
    
    if @keyword.save
      ProcessKeywordJob.perform_later(@keyword.id)
      redirect_to results_groups_path
    else
      redirect_to keywords_path
    end
  end

  def update
    @keyword = Keyword.find(params[:id])

    if @keyword.update(keyword_params)
      ProcessKeywordJob.perform_later(@keyword.id)
      redirect_to results_groups_path
    else
      redirect_to keywords_path
    end
  end

  def show
    group_stats = Analysis.all.map(&:stats)
    words = group_stats.map { |b| b&.values || 0 }.sum()

    render json: {
      group_stats: {
        users_analyzed: Analysis.count,
        mean: Analysis.mean(words),
        median: Analysis.median(words),
        std_dev: Analysis.std_dev(words)
      }
    }
  end

  def destroy
    @keyword = Keyword.find(params[:id])
    @keyword.destroy

    ProcessKeywordJob.perform_later("")
    redirect_to results_groups_path
  end

  private

  def keyword_params
    params.require(:keyword).permit(:word)
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_with model: keyword, url: keyword.persisted? ? keyword_path(keyword) : keywords_path do |f| %>
  <hr class="left-0 absolute w-full border-black">

  <section class="p-6 md:max-w-4xl">
    <div class="form-control my-2">
      <%= f.label :word, "Palavra Chave", class: 'label label-text text-black' %>
      <%= f.text_field :word, class: "input input-bordered" %>
    </div>

    <hr class="left-0 absolute w-full my-5 border-black">
  </section>

  <%= f.submit "Salvar", class: "btn rounded-lg bg-success text-white my-5 float-right" %>
<% end %>

app/views/keywords/index.html.erb
<div class="flex items-center m-5">
  <h1 class="text-2xl text-center text-primary mx-auto">
    Listagem de Palavras Chaves
  </h1>

  <button type="button" class="btn btn-success rounded-lg text-white" onclick="document.getElementById('criar_keyword').showModal();" title="Editar">
    Nova Palavra Chave
  </button>

  <dialog id="criar_keyword" class="modal place-items-center">
    <%= render "shared/modal", title: "Criar Palavra Chave", form_render: "keywords/form", keyword: @keyword %>
  </dialog>
</div>

<div class="flex flex-col mt-10">
  <div class="overflow-x-auto">
    <table class="table-auto w-full text-sm font-semibold text-center">
      <thead class="text-base">
        <tr>
          <th>ID</th>
          <th>Palavra Chave</th>
          <th>Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @keywords.each_with_index do |keyword, index| %>
          <tr class="border-t border-black items-center <%= index % 2 == 0 ? "bg-gray-200" : "bg-gray-100" %>">
            <td><%= keyword.id %></td>
            <td><%= keyword.word %></td>

            <td class="flex justify-center items-center gap-2 h-10">
              <button onclick="document.getElementById('edit_keyword<%= keyword.id %>').showModal();" title="Editar">
                <span class="material-symbols-outlined text-primary">edit</span>
              </button>

              <dialog id="edit_keyword<%= keyword.id %>" class="modal place-items-center">
                <%= render "shared/modal", title: "Editar Palavra Chave", form_render: "keywords/form", keyword: keyword %>
              </dialog>

              <%= link_to keyword_path(keyword), method: :delete,
                  data: { confirm: "Tem certeza que deseja apagar?" },
                  title: "Apagar definitivamente" do %>
                <span class="material-symbols-outlined text-primary">delete</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>