config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  root "home#index"

  resources :analyze, only: %i[index create update destroy]

  get "/results/:id", to: "analyze#show", as: :results
  get "/progress/:id", to: "analyze#progress", as: :progress
  get "/results_groups", to: "keywords#show", as: :results_groups

  resources :keywords, only: %i[index create update destroy]
  resources :users

  namespace :api do
    resources :users, only: %i[create]
    resources :keywords, only: %i[index create update destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="flex justify-center footer text-black items-center lg:h-20 md:h-16 border-t border-gray-300 fixed bottom-0 w-full bg-gray-200">
  <p>Desenvolvido por Renato Hernandez - 2025 - All right reserved</p>
</footer>

app/views/layouts/_header.html.erb
<div class="flex navbar bg-primary text-white justify-center fixed z-40">
  <a class="text-xl">Analisador de Comentários</a>
</div>

app/views/layouts/_sidebar.html.erb
<aside class="h-full bg-gray-200 overflow-y-auto border-r border-gray-300 text-black">
  <ul class="menu p-2 my-16">
    <li class="my-3">
      <%= link_to "Home", root_path, class: "nav-link #{'bg-primary text-white' if params[:controller] == 'home'}" %>
    </li>

    <li>
      <%= link_to "Palavras Chaves", keywords_path, class: "nav-link #{'bg-primary text-white' if params[:controller] == 'keywords'}" %>
    </li>

    <li>
      <%= link_to "Analises", analyze_index_path, class: "nav-link #{'bg-primary text-white' if params[:controller] == 'analyze'}" %>
    </li>

    <li>
      <%= link_to "Usuários", users_path, class: "nav-link #{'bg-primary text-white' if params[:controller] == 'users'}" %>
    </li>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommentAnalyzer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5/themes.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,200,0,0" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@400&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="grid grid-cols-12 h-screen">
      <div class="col-start-1">
        <%= render "layouts/sidebar" %>
      </div>

      <div class="col-start-2 col-span-12 p-5 my-20">
        <%= yield %>
      </div>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>